name: Docker image

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for building Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub (or another Docker registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secret for Docker Hub Username
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secret for Docker Hub Password

      # Step 4: Build and push the Docker image to DockerHub (or your registry)
      - name: Build and push Docker image
        run: |
          docker build -t yourdockerhubusername/node-app .
          docker push yourdockerhubusername/node-app

      # Optional: If deploying directly to your DigitalOcean droplet
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@139.59.94.150 << 'EOF'
            docker pull yourdockerhubusername/node-app
            docker run -d -p 80:80 --restart always --name node-app yourdockerhubusername/node-app
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secret for SSH private key
